// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "tags": [
                    "ping"
                ],
                "summary": "Проверка сервиса",
                "responses": {
                    "200": {
                        "description": "pong"
                    }
                }
            }
        },
        "/product/{productId}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Метод получения информации о конкретном продукте по его ID. Требуется авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получение информации о продукте",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID продукта",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Продукт успешно получен",
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    },
                    "400": {
                        "description": "Ошибка запроса, не удалось получить продукт"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Удаление продукта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID продукта для удаления",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Продукт успешно удален"
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "401": {
                        "description": "Не авторизован"
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получение списка продуктов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество продуктов на странице",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы для пагинации",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка продуктов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Product"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "401": {
                        "description": "Не авторизован"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Обновление информации о продукте",
                "parameters": [
                    {
                        "description": "Данные обновляемого продукта",
                        "name": "Product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Продукт успешно обновлен"
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "401": {
                        "description": "Не авторизован"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Добавление нового продукта",
                "parameters": [
                    {
                        "description": "Данные нового продукта",
                        "name": "Product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Продукт успешно добавлен"
                    },
                    "400": {
                        "description": "Ошибка запроса"
                    },
                    "401": {
                        "description": "Не авторизован"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Brand": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id бренда кроссовок",
                    "type": "integer"
                },
                "name": {
                    "description": "Наименование бренда",
                    "type": "string"
                }
            }
        },
        "domain.Factory": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Конкретный адрес",
                    "type": "string"
                },
                "city": {
                    "description": "Город",
                    "type": "string"
                },
                "country": {
                    "description": "Страна",
                    "type": "string"
                },
                "id": {
                    "description": "Id завода изготовителя",
                    "type": "integer"
                },
                "name": {
                    "description": "Название завода",
                    "type": "string"
                }
            }
        },
        "domain.Product": {
            "type": "object",
            "properties": {
                "brand": {
                    "description": "Бренд кроссовок",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Brand"
                        }
                    ]
                },
                "description": {
                    "description": "Описание модели кроссовка",
                    "type": "string"
                },
                "factory": {
                    "description": "Завод изготовитель",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Factory"
                        }
                    ]
                },
                "id": {
                    "description": "Id продукта",
                    "type": "integer"
                },
                "images": {
                    "description": "Картинки",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductImage"
                    }
                },
                "items": {
                    "description": "Варианты кроссовок",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductItem"
                    }
                },
                "materials": {
                    "description": "Материалы изготовления",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductMaterial"
                    }
                },
                "name": {
                    "description": "Название модели кроссовка",
                    "type": "string"
                },
                "price": {
                    "description": "Цена продукта",
                    "type": "number"
                }
            }
        },
        "domain.ProductImage": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id картинки",
                    "type": "integer"
                },
                "imageUrl": {
                    "description": "Ссылка на ресурс с картинкой",
                    "type": "string"
                }
            }
        },
        "domain.ProductItem": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "Цвет",
                    "type": "string"
                },
                "id": {
                    "description": "Id варианта кроссовка",
                    "type": "integer"
                },
                "size": {
                    "description": "Размер",
                    "type": "integer"
                },
                "stockCount": {
                    "description": "Кол-во на складе",
                    "type": "integer"
                },
                "weight": {
                    "description": "Вес",
                    "type": "number"
                }
            }
        },
        "domain.ProductMaterial": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id материала",
                    "type": "integer"
                },
                "name": {
                    "description": "Название материала",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "storage-service",
	Description:      "Сервис управления продукцией на складе для goat-logistics",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
