definitions:
  domain.Brand:
    properties:
      id:
        description: Id бренда кроссовок
        type: integer
      name:
        description: Наименование бренда
        type: string
    type: object
  domain.Factory:
    properties:
      address:
        description: Конкретный адрес
        type: string
      city:
        description: Город
        type: string
      country:
        description: Страна
        type: string
      id:
        description: Id завода изготовителя
        type: integer
      name:
        description: Название завода
        type: string
    type: object
  domain.Product:
    properties:
      brand:
        allOf:
        - $ref: '#/definitions/domain.Brand'
        description: Бренд кроссовок
      description:
        description: Описание модели кроссовка
        type: string
      factory:
        allOf:
        - $ref: '#/definitions/domain.Factory'
        description: Завод изготовитель
      id:
        description: Id продукта
        type: integer
      images:
        description: Картинки
        items:
          $ref: '#/definitions/domain.ProductImage'
        type: array
      items:
        description: Варианты кроссовок
        items:
          $ref: '#/definitions/domain.ProductItem'
        type: array
      materials:
        description: Материалы изготовления
        items:
          $ref: '#/definitions/domain.ProductMaterial'
        type: array
      name:
        description: Название модели кроссовка
        type: string
      price:
        description: Цена продукта
        type: number
    type: object
  domain.ProductImage:
    properties:
      id:
        description: Id картинки
        type: integer
      imageUrl:
        description: Ссылка на ресурс с картинкой
        type: string
    type: object
  domain.ProductItem:
    properties:
      color:
        description: Цвет
        type: string
      id:
        description: Id варианта кроссовка
        type: integer
      size:
        description: Размер
        type: integer
      stockCount:
        description: Кол-во на складе
        type: integer
      weight:
        description: Вес
        type: number
    type: object
  domain.ProductMaterial:
    properties:
      id:
        description: Id материала
        type: integer
      name:
        description: Название материала
        type: string
    type: object
info:
  contact: {}
  description: Сервис управления продукцией на складе для goat-logistics
  title: storage-service
  version: "1.0"
paths:
  /ping:
    get:
      responses:
        "200":
          description: pong
      summary: Проверка сервиса
      tags:
      - ping
  /product/{productId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID продукта для удаления
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Продукт успешно удален
        "400":
          description: Ошибка запроса
        "401":
          description: Не авторизован
      security:
      - Bearer: []
      summary: Удаление продукта
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Метод получения информации о конкретном продукте по его ID. Требуется
        авторизация.
      parameters:
      - description: ID продукта
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Продукт успешно получен
          schema:
            $ref: '#/definitions/domain.Product'
        "400":
          description: Ошибка запроса, не удалось получить продукт
        "401":
          description: Пользователь не авторизован
      security:
      - Bearer: []
      summary: Получение информации о продукте
      tags:
      - products
  /products:
    get:
      consumes:
      - application/json
      parameters:
      - description: Количество продуктов на странице
        in: query
        name: limit
        required: true
        type: integer
      - description: Номер страницы для пагинации
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешное получение списка продуктов
          schema:
            items:
              $ref: '#/definitions/domain.Product'
            type: array
        "400":
          description: Ошибка запроса
        "401":
          description: Не авторизован
      security:
      - Bearer: []
      summary: Получение списка продуктов
      tags:
      - products
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные нового продукта
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      produces:
      - application/json
      responses:
        "200":
          description: Продукт успешно добавлен
        "400":
          description: Ошибка запроса
        "401":
          description: Не авторизован
      security:
      - Bearer: []
      summary: Добавление нового продукта
      tags:
      - products
    put:
      consumes:
      - application/json
      parameters:
      - description: Данные обновляемого продукта
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      produces:
      - application/json
      responses:
        "200":
          description: Продукт успешно обновлен
        "400":
          description: Ошибка запроса
        "401":
          description: Не авторизован
      security:
      - Bearer: []
      summary: Обновление информации о продукте
      tags:
      - products
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
